services:
  db:
    image: postgres:15-alpine
    container_name: urbanride_db
    restart: always
    environment:
      POSTGRES_USER: urbanride
      POSTGRES_PASSWORD: sua_senha_aqui
      POSTGRES_DB: urbanride_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U urbanride"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: